name: 🐛 Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: "I clicked X and Y happened..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How do we reproduce the behavior?
      placeholder: |
        Please write the steps taken to reproduce this bug here. Also add the your enviroment setting like the OS you are working on, the python version your using etc..
    validations:
      required: true

  - type: dropdown
      id: severity
      attributes:
        label: Severity / Priority
        description: How much does this affect the user experience?
        options:
          - Critical (Crash / Data Loss)
          - Major (Feature Broken)
          - Minor (Annoyance / UI Glitch)
          - Trivial (Typo)
      validations:
        required: true
