# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

clean:
	@test -n "$(BUILDDIR)" || (echo "ERROR: BUILDDIR is empty" && exit 1)
	@test -d "$(BUILDDIR)" || (echo "ERROR: BUILDDIR does not exist" && exit 1)
	@test "$(BUILDDIR)" != "/" || (echo "ERROR: BUILDDIR is root" && exit 1)
	rm -rf "$(BUILDDIR)"
	mkdir -p "$(BUILDDIR)"

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
